# Generated by Django 3.0.14 on 2023-02-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='YourPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=256)),
                ('pic', models.ImageField(blank=True, upload_to='basic_app/profile_pics')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to='basic_app.YourEnvironment')),
            ],
        ),
    ]
