# Generated by Django 3.0.14 on 2023-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20230221_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourpics',
            name='pic',
        ),
        migrations.AddField(
            model_name='yourpics',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='photos/all/'),
        ),
    ]
