# Generated by Django 3.0.14 on 2023-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20230221_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourpics',
            name='image_desc',
            field=models.CharField(default='', max_length=256),
        ),
    ]
