# Generated by Django 3.0.14 on 2023-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_yourpics_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourpics',
            name='image',
            field=models.ImageField(default='', upload_to='photos/all/'),
        ),
        migrations.AlterField(
            model_name='yourpics',
            name='image_desc',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
