# Generated by Django 3.0.14 on 2023-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20230221_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourpics',
            old_name='name2',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='yourpics',
            old_name='image_desc',
            new_name='image_description',
        ),
        migrations.AlterField(
            model_name='yourpics',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/all/'),
        ),
    ]
